# ==================== CONFIG IMPORT (carica env.properties) ====================
spring.config.import=optional:file:./env.properties
# ==================== APPLICATION ====================
spring.application.name=registro-elettronico-backend
server.port=${PORT}
# ==================== DATABASE CONFIGURATION (PostgreSQL) ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ==================== JPA/HIBERNATE CONFIGURATION ====================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# PRODUCTION: usa 'validate' o 'none'
# DEVELOPMENT: usa 'create' (ricrea DB) o 'update' (aggiorna schema)
# ==================== JWT CONFIGURATION ====================
jwt.secret=${JWT_SECRET}
jwt.expirationms=${JWT_EXPIRATION_MS:604800000}
# ==================== UTENTE ADMIN RUNNER  ====================
admin.email=${ADMIN_EMAIL}
admin.pwd=${ADMIN_PWD}
admin.dateOfBirth=${ADMIN_DATE_OF_BIRTH}
admin.name=${ADMIN_NAME}
admin.lastname=${ADMIN_LASTNAME}
# ==================== CLOUDINARY CONFIG ====================
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
# ==================== MAILGUN CONFIG ====================
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.apiKey=${MAILGUN_API_KEY}